import 'dart:io';

import 'package:path/path.dart' as p;

import '../api/api_config.dart';
import '../api/api_protocol.dart';

/// Contract-codegen stubs (7e) — protocol-based README pointers only.
Map<String, String> contractCodegenStubFiles({
  required ApiConfig api,
}) {
  final files = <String, String>{};

  if (api.protocol == ApiProtocol.rest || api.protocol == ApiProtocol.mixed) {
    files['doc/contracts/openapi.md'] = '''
# OpenAPI / REST contract

Add your OpenAPI schema under `contracts/openapi.yaml` and generate clients locally.

```bash
# Example: openapi-generator or your preferred tool
```
''';
  }

  if (api.protocol == ApiProtocol.grpc || api.secondaryProtocol == ApiProtocol.grpc) {
    files['doc/contracts/proto.md'] = '''
# gRPC / Protobuf

Place `.proto` files under `contracts/proto/` and run `protoc` locally.
''';
  }

  if (api.protocol == ApiProtocol.graphql ||
      api.secondaryProtocol == ApiProtocol.graphql) {
    files['doc/contracts/graphql.md'] = '''
# GraphQL schema

Place `schema.graphql` under `contracts/graphql/` and use your codegen tool locally.
''';
  }

  return files;
}

String architectureGuardrailsSnippet() {
  return '''
# Architecture guardrails (generated by Flutter Project Setup Toolkit)
# Merge into analysis_options.yaml under analyzer.errors / linter.rules as needed.

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_relative_lib_imports
    - depend_on_referenced_packages
    # Add custom_lint package rules when you adopt a rules package locally.
''';
}

Future<void> writeGuardrailsSnippetIfMissing(Directory projectRoot) async {
  final file = File(p.join(projectRoot.path, 'analysis_options.toolkit.yaml'));
  if (file.existsSync()) return;
  file.writeAsStringSync(architectureGuardrailsSnippet());
}
