import 'dart:io';

import 'package:path/path.dart' as p;

import 'api_config.dart';
import 'api_protocol.dart';

class ApiScaffoldResult {
  ApiScaffoldResult({
    required this.createdPaths,
    required this.dryRun,
  });

  final List<String> createdPaths;
  final bool dryRun;
}

Future<ApiScaffoldResult> scaffoldApiLayer({
  required Directory projectRoot,
  required ApiConfig config,
  bool dryRun = false,
}) async {
  final created = <String>[];
  final files = _globalApiFiles(config);

  for (final relative in files) {
    final display = relative;
    if (dryRun) {
      created.add(display);
      continue;
    }
    final file = File(p.join(projectRoot.path, relative));
    if (file.existsSync()) continue;
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(_stubContent(relative, config));
    created.add(display);
  }

  return ApiScaffoldResult(createdPaths: created, dryRun: dryRun);
}

List<String> _globalApiFiles(ApiConfig config) {
  if (config.usesExternalSdk) {
    return [
      'lib/core/sdk/sdk_config.dart',
      'lib/core/sdk/sdk_bootstrap.dart',
      if (config.externalSdk?.packageName.isNotEmpty ?? false)
        'lib/core/sdk/${config.externalSdk!.packageName}_adapter.dart',
      'lib/core/errors/api_exceptions.dart',
    ];
  }

  final files = <String>['lib/core/errors/api_exceptions.dart'];

  if (config.protocol == ApiProtocol.rest ||
      config.protocol == ApiProtocol.mixed) {
    if (config.restClient == RestClientStyle.dio) {
      files.add('lib/core/network/dio_client.dart');
    } else {
      files.add('lib/core/network/http_client.dart');
    }
  }
  if (config.protocol == ApiProtocol.grpc ||
      config.protocol == ApiProtocol.mixed) {
    files.add('lib/core/network/grpc_client.dart');
  }
  if (config.protocol == ApiProtocol.graphql) {
    files.add('lib/core/network/graphql_client.dart');
  }
  if (config.protocol == ApiProtocol.websocket ||
      config.realtime == RealtimeStyle.websocket) {
    files.add('lib/core/network/websocket_service.dart');
  }
  if (config.protocol == ApiProtocol.firebase) {
    files.add('lib/core/network/firebase_initializer.dart');
  }
  if (config.protocol == ApiProtocol.supabase) {
    files.add('lib/core/network/supabase_client.dart');
  }

  if (config.protocol != ApiProtocol.localOnly) {
    files.add('lib/core/network/network_info.dart');
  }

  switch (config.localCache) {
    case LocalCacheStyle.hive:
    case LocalCacheStyle.drift:
    case LocalCacheStyle.isar:
      files.add('lib/core/storage/local_database.dart');
    case LocalCacheStyle.sharedPreferences:
      files.add('lib/core/storage/preferences_storage.dart');
    case LocalCacheStyle.none:
      break;
  }

  return files;
}

String _stubContent(String relativePath, ApiConfig config) {
  if (relativePath.endsWith('sdk_bootstrap.dart')) {
    final hint = config.externalSdk?.initHint ?? '// Initialize external SDK';
    return '''
// SDK bootstrap — generated by Flutter Project Setup Toolkit
$hint
''';
  }
  if (relativePath.endsWith('_adapter.dart')) {
    final pkg = config.externalSdk?.packageName ?? 'external_sdk';
    return '''
// Adapter for package:$pkg
// import 'package:$pkg/$pkg.dart';
''';
  }
  if (relativePath.endsWith('dio_client.dart')) {
    return '''
// Dio HTTP client — configure base URL via ${config.baseUrlEnvKey}
''';
  }
  return '';
}

String envApiTemplateLine(ApiConfig config) {
  final line = config.envLineForProtocol();
  if (line != null) return line;
  if (config.realtime == RealtimeStyle.websocket) {
    return '${config.websocketUrlEnvKey}=';
  }
  return '';
}
