import 'dart:io';

import 'package:path/path.dart' as p;

import '../ci/ci_diff.dart';
import 'project_docs_context.dart';
import 'project_docs_generators.dart';
import 'project_docs_marker.dart';
import 'project_docs_spec.dart';

class ProjectDocsService {
  Map<String, dynamic> detect(Directory projectRoot) {
    final ctx = gatherProjectDocsContext(projectRoot);
    final spec = ProjectDocsSpec.defaults();
    final generated = generateProjectDocsFiles(ctx: ctx, spec: spec);
    final missing = <String>[];
    final existing = <String>[];
    for (final path in ProjectDocsPaths.all) {
      if (ctx.existingDocs[path] == true) {
        existing.add(path);
      } else {
        missing.add(path);
      }
    }

    final substantialReadme = isSubstantialCustomReadme(ctx.existingReadme);

    return {
      'context': ctx.toJson(),
      'missing_docs': missing,
      'existing_docs': existing,
      'substantial_readme': substantialReadme,
      'default_spec': spec.toJson(),
      'doc_paths': ProjectDocsPaths.all,
      'doc_labels': ProjectDocsPaths.labels,
      'preview_lengths': {
        for (final entry in generated.entries) entry.key: entry.value.length,
      },
    };
  }

  Map<String, dynamic> preview({
    required Directory projectRoot,
    required ProjectDocsSpec spec,
  }) {
    final ctx = gatherProjectDocsContext(projectRoot);
    final files = generateProjectDocsFiles(ctx: ctx, spec: spec);
    final diffs = <String, String>{};
    final skipReasons = <String, String>{};

    for (final entry in files.entries) {
      final file = File(p.join(projectRoot.path, entry.key));
      if (file.existsSync()) {
        diffs[entry.key] = unifiedDiff(
          oldText: file.readAsStringSync(),
          newText: entry.value,
          oldLabel: entry.key,
          newLabel: '${entry.key} (generated)',
        );
      }
      final reason = _skipReason(
        path: entry.key,
        exists: file.existsSync(),
        existingContent: file.existsSync() ? file.readAsStringSync() : null,
        policy: spec.overwritePolicy,
        ctx: ctx,
      );
      if (reason != null) {
        skipReasons[entry.key] = reason;
      }
    }

    return {
      'files': files,
      'diffs': diffs,
      'skip_reasons': skipReasons,
      'would_write': files.keys
          .where((path) => !skipReasons.containsKey(path))
          .toList(),
      'substantial_readme': isSubstantialCustomReadme(ctx.existingReadme),
      if (isSubstantialCustomReadme(ctx.existingReadme) &&
          files.containsKey(ProjectDocsPaths.readme))
        'proposed_readme': files[ProjectDocsPaths.readme],
    };
  }

  Map<String, dynamic> write({
    required Directory projectRoot,
    required ProjectDocsSpec spec,
  }) {
    final ctx = gatherProjectDocsContext(projectRoot);
    final files = generateProjectDocsFiles(ctx: ctx, spec: spec);
    final written = <String>[];
    final skipped = <String, String>{};

    for (final entry in files.entries) {
      final file = File(p.join(projectRoot.path, entry.key));
      final exists = file.existsSync();
      final existingContent = exists ? file.readAsStringSync() : null;

      final reason = _skipReason(
        path: entry.key,
        exists: exists,
        existingContent: existingContent,
        policy: spec.overwritePolicy,
        ctx: ctx,
      );
      if (reason != null) {
        skipped[entry.key] = reason;
        continue;
      }

      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
      written.add(entry.key);
    }

    return {
      'written': written,
      'skipped': skipped,
      'project_path': projectRoot.path,
    };
  }

  String? _skipReason({
    required String path,
    required bool exists,
    required String? existingContent,
    required ProjectDocsOverwritePolicy policy,
    required ProjectDocsContext ctx,
  }) {
    if (!exists) return null;

    switch (policy) {
      case ProjectDocsOverwritePolicy.overwriteAll:
        return null;
      case ProjectDocsOverwritePolicy.refreshGenerated:
        if (existingContent != null && isProjectDocsGenerated(existingContent)) {
          return null;
        }
        return 'File exists and was not generated by Docs Studio';
      case ProjectDocsOverwritePolicy.skipExisting:
        if (path == ProjectDocsPaths.readme &&
            isSubstantialCustomReadme(ctx.existingReadme)) {
          return 'README has substantial custom content';
        }
        return 'File already exists';
    }
  }
}
