import '../config.dart';
import 'ci_provider.dart';
import 'ci_template_shared.dart';
import 'ci_workflow_spec.dart';

Map<String, String> generateAzurePipelinesFiles({
  required CiWorkflowSpec spec,
  required ToolkitConfig config,
}) {
  final ubuntuVm = providerConfigString(
    spec.providerConfig,
    'ubuntu_vm_image',
    fallback: 'ubuntu-latest',
  );
  final macosVm = providerConfigString(
    spec.providerConfig,
    'macos_vm_image',
    fallback: 'macOS-latest',
  );

  final stages = <String>[];

  if (spec.hasCiJobs) {
    final analyzeCmds = sharedAnalyzeCommands(spec);
    stages.add('''
- stage: Test
  displayName: Quality gates
  jobs:
  - job: Analyze
    pool:
      vmImage: $ubuntuVm
    steps:
    - checkout: self
    - task: FlutterInstall@0
      inputs:
        channel: stable
    - script: |
${analyzeCmds.map((c) => '        $c').join('\n')}
      displayName: Run checks
''');
  }

  if (spec.hasReleaseJobs) {
    final releaseJobs = <String>[];
    if (spec.androidAab) {
      releaseJobs.add('''
  - job: AndroidRelease
    pool:
      vmImage: $ubuntuVm
    steps:
    - checkout: self
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: x64
        jdkSourceOption: PreInstalled
    - task: FlutterInstall@0
      inputs:
        channel: stable
    - script: |
        echo "\$(ENV_FILE)" > .env.ci
        export ENV_FILE_PATH=.env.ci
        flutter pub get
        ${sharedAndroidBuildCommand(spec, config)}
      displayName: Build AAB
      env:
        ENV_FILE: \$(ENV_FILE)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: build/app/outputs/bundle
        artifact: android-aab
''');
    }
    if (spec.iosIpa) {
      releaseJobs.add('''
  - job: iOSRelease
    pool:
      vmImage: $macosVm
    steps:
    - checkout: self
    - task: FlutterInstall@0
      inputs:
        channel: stable
    - script: |
        echo "\$(ENV_FILE)" > .env.ci
        export ENV_FILE_PATH=.env.ci
        flutter pub get
        cd ios && pod install && cd ..
        ${sharedIosBuildCommand(spec, config)}
      displayName: Build IPA
      env:
        ENV_FILE: \$(ENV_FILE)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: build/ios/ipa
        artifact: ios-ipa
''');
    }
    stages.add('''
- stage: Release
  displayName: Build artifacts${spec.hasCiJobs ? '\n  dependsOn: Test\n  condition: succeeded()' : ''}
  jobs:
${releaseJobs.join('\n')}
''');
  }

  final triggerBlock = spec.onPullRequest
      ? '''
pr:
  branches:
    include:
    - main
    - master
'''
      : '';

  final yaml = '''
# Generated by Flutter Project Setup Toolkit — Azure Pipelines
# Docs: https://learn.microsoft.com/en-us/azure/devops/pipelines/
# Add ENV_FILE as a secret pipeline variable

trigger:
  branches:
    include:
    - main
    - master
$triggerBlock
stages:
${stages.join('\n')}
''';

  return {'azure-pipelines.yml': yaml};
}
