import '../config.dart';
import 'ci_provider.dart';
import 'ci_template_shared.dart';
import 'ci_workflow_spec.dart';

Map<String, String> generateBitbucketPipelinesFiles({
  required CiWorkflowSpec spec,
  required ToolkitConfig config,
}) {
  final size = providerConfigString(
    spec.providerConfig,
    'size',
    fallback: '2x',
  );

  final pipelines = <String>[];

  if (spec.hasCiJobs) {
    final analyzeCmds = sharedAnalyzeCommands(spec);
    pipelines.add('''
    default:
      - step:
          name: Quality gates
          image: ghcr.io/cirruslabs/flutter:stable
          size: $size
          script:
${yamlScriptBlock(analyzeCmds, indent: '            ')}
''');
  }

  if (spec.androidAab || spec.iosIpa) {
    final releaseSteps = <String>[];
    if (spec.androidAab) {
      releaseSteps.add('''
      - step:
          name: Android AAB
          image: ghcr.io/cirruslabs/flutter:stable
          size: $size
          script:
            - apt-get update && apt-get install -y openjdk-17-jdk
            - echo "\$ENV_FILE" > .env.ci
            - export ENV_FILE_PATH=.env.ci
            - flutter pub get
            - ${sharedAndroidBuildCommand(spec, config)}
          artifacts:
            - build/app/outputs/bundle/**
''');
    }
    if (spec.iosIpa) {
      releaseSteps.add('''
      - step:
          name: iOS IPA
          runs-on:
            - self.hosted
            - macos
          script:
            - echo "\$ENV_FILE" > .env.ci
            - export ENV_FILE_PATH=.env.ci
            - flutter pub get
            - cd ios && pod install && cd ..
            - ${sharedIosBuildCommand(spec, config)}
          artifacts:
            - build/ios/ipa/**
''');
    }
    pipelines.add('''
    branches:
      main:
${releaseSteps.join('\n')}
      master:
${releaseSteps.join('\n')}
''');
  }

  final yaml = '''
# Generated by Flutter Project Setup Toolkit — Bitbucket Pipelines
# Docs: https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines/
# Repository settings → Pipelines → Repository variables: ENV_FILE

image: ghcr.io/cirruslabs/flutter:stable

pipelines:
${pipelines.join('\n')}
''';

  return {'bitbucket-pipelines.yml': yaml};
}
