import 'dart:io';

import 'package:path/path.dart' as p;

import 'ci_readiness.dart';
import 'ci_secrets_checklist.dart';
import 'ci_test_models.dart';
import 'ci_tooling_detect.dart';
import 'ci_workflow_paths.dart';
import 'ci_provider.dart';
import 'ci_workflow_spec.dart';

class CiPublishResult {
  CiPublishResult({
    required this.branch,
    required this.workflowPaths,
    required this.secretsRequired,
    this.prUrl,
    this.committed = false,
    this.pushed = false,
    this.readmeBadge,
    this.branchProtectionHint,
    this.ciSetupPath,
    this.manualNextSteps,
  });

  final String branch;
  final List<String> workflowPaths;
  final List<Map<String, dynamic>> secretsRequired;
  final String? prUrl;
  final bool committed;
  final bool pushed;
  final String? readmeBadge;
  final String? branchProtectionHint;
  final String? ciSetupPath;
  final List<String>? manualNextSteps;

  Map<String, dynamic> toJson() => {
        'branch': branch,
        'workflow_paths': workflowPaths,
        'secrets_required': secretsRequired,
        if (prUrl != null) 'pr_url': prUrl,
        'committed': committed,
        'pushed': pushed,
        if (readmeBadge != null) 'readme_badge': readmeBadge,
        if (branchProtectionHint != null)
          'branch_protection_hint': branchProtectionHint,
        if (ciSetupPath != null) 'ci_setup_path': ciSetupPath,
        if (manualNextSteps != null) 'manual_next_steps': manualNextSteps,
      };
}

class CiPublishBlockedException implements Exception {
  CiPublishBlockedException(this.message);
  final String message;
  @override
  String toString() => message;
}

Future<CiPublishResult> publishCiWorkflow({
  required Directory projectRoot,
  required CiTestJobState testState,
  required CiWorkflowSpec spec,
  required List<String> writtenPaths,
  Map<String, String>? envPaths,
}) async {
  if (!testState.passed) {
    throw CiPublishBlockedException(
      'Publish blocked: local test must pass before publishing',
    );
  }

  if (_which('git') == null) {
    throw CiPublishBlockedException('git is required to publish');
  }

  final providerInfo = ciProviderInfo(spec.provider);
  if (providerInfo.supportsGhPublish) {
    return _publishViaGitHubPr(
      projectRoot: projectRoot,
      spec: spec,
      writtenPaths: writtenPaths,
      envPaths: envPaths,
    );
  }
  return _publishGeneric(
    projectRoot: projectRoot,
    spec: spec,
    writtenPaths: writtenPaths,
    envPaths: envPaths,
    providerInfo: providerInfo,
  );
}

Future<CiPublishResult> _publishViaGitHubPr({
  required Directory projectRoot,
  required CiWorkflowSpec spec,
  required List<String> writtenPaths,
  Map<String, String>? envPaths,
}) async {
  final tooling = await detectCiTooling();
  final gh = tooling['gh'] as Map<String, dynamic>;
  if (gh['authenticated'] != true) {
    throw CiPublishBlockedException(
      gh['hint'] as String? ?? 'gh CLI must be authenticated',
    );
  }

  final remote = await detectGitHubRemote(projectRoot);
  if (remote == null || remote['is_github'] != true) {
    throw CiPublishBlockedException(
      'origin must point to a GitHub repository to open a pull request',
    );
  }

  final branch = await _resolvePublishBranch(projectRoot);
  if (branch != await _currentBranch(projectRoot)) {
    await _runGit(projectRoot, ['checkout', '-B', branch]);
  }

  final toAdd = <String>[
    ...writtenPaths,
    if (File(p.join(projectRoot.path, CiWorkflowPaths.ciSetupDoc)).existsSync())
      CiWorkflowPaths.ciSetupDoc,
    if (File(p.join(projectRoot.path, 'fastlane', 'Fastfile')).existsSync())
      'fastlane/Fastfile',
  ];

  await _runGit(projectRoot, ['add', ...toAdd]);

  final status = await Process.run(
    'git',
    ['status', '--porcelain'],
    workingDirectory: projectRoot.path,
  );
  if (status.stdout.toString().trim().isEmpty) {
    throw CiPublishBlockedException('No workflow changes to commit');
  }

  await _runGit(projectRoot, [
    'commit',
    '-m',
    'Add Flutter CI workflow',
  ]);

  await _runGit(projectRoot, ['push', '-u', 'origin', branch]);

  final secrets = ciSecretsChecklist(spec: spec, envPaths: envPaths);
  final jobs = <String>[];
  if (spec.analyze) jobs.add('analyze');
  if (spec.formatCheck) jobs.add('format check');
  if (spec.architectureAudit) jobs.add('architecture audit');
  if (spec.androidAab) jobs.add('Android AAB');
  if (spec.iosIpa) jobs.add('iOS IPA');

  final prBody = StringBuffer()
    ..writeln('## Summary')
    ..writeln()
    ..writeln('Adds Flutter CI/CD workflows generated by CI Studio.')
    ..writeln()
    ..writeln('**Jobs:** ${jobs.join(', ')}')
    ..writeln()
    ..writeln('## Secrets checklist')
    ..writeln();
  for (final secret in secrets) {
    final tag = secret.required ? 'required' : 'optional';
    prBody.writeln('- `${secret.name}` ($tag) — ${secret.description}');
  }
  prBody
    ..writeln()
    ..writeln('Local smoke test passed before publish.');

  final prResult = await Process.run(
    'gh',
    [
      'pr',
      'create',
      '--title',
      'Add Flutter CI workflow',
      '--body',
      prBody.toString(),
    ],
    workingDirectory: projectRoot.path,
  );
  if (prResult.exitCode != 0) {
    throw CiPublishBlockedException(
      'gh pr create failed: ${prResult.stderr}',
    );
  }

  final prUrl = prResult.stdout.toString().trim();

  final owner = remote['owner'] as String?;
  final repo = remote['repo'] as String?;
  final badge = owner != null && repo != null
      ? readmeBadgeSnippet(owner, repo)
      : null;

  return CiPublishResult(
    branch: branch,
    workflowPaths: writtenPaths,
    secretsRequired: secrets.map((s) => s.toJson()).toList(),
    prUrl: prUrl.isEmpty ? null : prUrl,
    committed: true,
    pushed: true,
    readmeBadge: badge,
    branchProtectionHint: ciBranchProtectionHint(),
    ciSetupPath: File(p.join(projectRoot.path, CiWorkflowPaths.ciSetupDoc))
            .existsSync()
        ? CiWorkflowPaths.ciSetupDoc
        : null,
  );
}

Future<CiPublishResult> _publishGeneric({
  required Directory projectRoot,
  required CiWorkflowSpec spec,
  required List<String> writtenPaths,
  Map<String, String>? envPaths,
  required CiProviderInfo providerInfo,
}) async {
  final branch = await _resolvePublishBranch(projectRoot);
  if (branch != await _currentBranch(projectRoot)) {
    await _runGit(projectRoot, ['checkout', '-B', branch]);
  }

  final toAdd = <String>[
    ...writtenPaths,
    if (File(p.join(projectRoot.path, CiWorkflowPaths.ciSetupDoc)).existsSync())
      CiWorkflowPaths.ciSetupDoc,
    if (File(p.join(projectRoot.path, 'fastlane', 'Fastfile')).existsSync())
      'fastlane/Fastfile',
  ];

  await _runGit(projectRoot, ['add', ...toAdd]);

  final status = await Process.run(
    'git',
    ['status', '--porcelain'],
    workingDirectory: projectRoot.path,
  );
  if (status.stdout.toString().trim().isEmpty) {
    throw CiPublishBlockedException('No workflow changes to commit');
  }

  await _runGit(projectRoot, [
    'commit',
    '-m',
    'Add Flutter CI pipeline (${providerInfo.label})',
  ]);

  await _runGit(projectRoot, ['push', '-u', 'origin', branch]);

  final secrets = ciSecretsChecklist(spec: spec, envPaths: envPaths);

  return CiPublishResult(
    branch: branch,
    workflowPaths: writtenPaths,
    secretsRequired: secrets.map((s) => s.toJson()).toList(),
    committed: true,
    pushed: true,
    ciSetupPath: File(p.join(projectRoot.path, CiWorkflowPaths.ciSetupDoc))
            .existsSync()
        ? CiWorkflowPaths.ciSetupDoc
        : null,
    manualNextSteps: [
      'Open ${providerInfo.label} and confirm the pipeline ran on branch `$branch`.',
      'Configure secrets/variables listed in CI_SETUP.md in the ${providerInfo.label} UI.',
      'Docs: ${providerInfo.docsUrl}',
    ],
  );
}

Future<String> _resolvePublishBranch(Directory projectRoot) async {
  final current = await _currentBranch(projectRoot);
  if (current == 'main' || current == 'master' || current == 'HEAD') {
    return 'rtk/ci-workflow';
  }
  return current;
}

Future<String> _currentBranch(Directory projectRoot) async {
  final result = await Process.run(
    'git',
    ['rev-parse', '--abbrev-ref', 'HEAD'],
    workingDirectory: projectRoot.path,
  );
  if (result.exitCode != 0) return 'HEAD';
  return result.stdout.toString().trim();
}

Future<void> _runGit(Directory projectRoot, List<String> args) async {
  final result = await Process.run(
    'git',
    args,
    workingDirectory: projectRoot.path,
  );
  if (result.exitCode != 0) {
    throw CiPublishBlockedException(
      'git ${args.first} failed: ${result.stderr}',
    );
  }
}

String? _which(String name) {
  final result = Process.runSync('which', [name]);
  if (result.exitCode != 0) return null;
  final path = result.stdout.toString().trim();
  return path.isEmpty ? null : path;
}
