import 'ci_workflow_spec.dart';

class CiSecretItem {
  CiSecretItem({
    required this.id,
    required this.name,
    required this.description,
    this.required = false,
    this.optional = false,
  });

  final String id;
  final String name;
  final String description;
  final bool required;
  final bool optional;

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'description': description,
        'required': required,
        'optional': optional,
      };
}

List<CiSecretItem> ciSecretsChecklist({
  required CiWorkflowSpec spec,
  Map<String, String>? envPaths,
}) {
  final items = <CiSecretItem>[];

  if (spec.androidAab || spec.iosIpa) {
    items.add(
      CiSecretItem(
        id: 'env_file',
        name: 'ENV_FILE',
        description: envPaths != null && envPaths.isNotEmpty
            ? 'Full contents of ${envPaths[spec.defaultEnv] ?? envPaths.values.first} '
                'for --dart-define-from-file in CI'
            : 'Full contents of your production/staging env file for --dart-define-from-file',
        required: true,
      ),
    );
  }

  if (spec.androidAab) {
    items.addAll([
      CiSecretItem(
        id: 'android_keystore',
        name: 'ANDROID_KEYSTORE_BASE64',
        description: 'Base64-encoded release keystore (optional if using debug signing in CI)',
        optional: true,
      ),
      CiSecretItem(
        id: 'android_keystore_password',
        name: 'ANDROID_KEYSTORE_PASSWORD',
        description: 'Keystore password',
        optional: true,
      ),
    ]);
  }

  if (spec.iosIpa) {
    items.addAll([
      CiSecretItem(
        id: 'match_password',
        name: 'MATCH_PASSWORD',
        description: 'Fastlane Match password for iOS certificates',
        optional: true,
      ),
      CiSecretItem(
        id: 'app_store_connect',
        name: 'APP_STORE_CONNECT_API_KEY',
        description: 'App Store Connect API key JSON for TestFlight upload',
        optional: true,
      ),
    ]);
  }

  if (spec.firebaseAppDistribution) {
    items.add(
      CiSecretItem(
        id: 'firebase_service_account',
        name: 'FIREBASE_SERVICE_ACCOUNT',
        description: 'Firebase service account JSON for App Distribution',
        optional: true,
      ),
    );
  }

  return items;
}

String readmeBadgeSnippet(String owner, String repo, {String workflow = 'flutter-release.yml'}) {
  return '![Flutter release](https://github.com/$owner/$repo/actions/workflows/$workflow/badge.svg)';
}

String generateCiSetupMarkdown({
  required CiWorkflowSpec spec,
  required List<CiSecretItem> secrets,
  String? githubOwner,
  String? githubRepo,
}) {
  final jobs = <String>[];
  if (spec.analyze) jobs.add('analyze');
  if (spec.formatCheck) jobs.add('format check');
  if (spec.architectureAudit) jobs.add('architecture audit');
  if (spec.androidAab) jobs.add('Android AAB');
  if (spec.iosIpa) jobs.add('iOS IPA');
  if (spec.firebaseAppDistribution) jobs.add('Firebase App Distribution');

  final buffer = StringBuffer()
    ..writeln('# CI setup')
    ..writeln()
    ..writeln('Generated by Flutter Project Setup Toolkit CI Studio.')
    ..writeln()
    ..writeln('## Enabled jobs')
    ..writeln()
    ..writeln(jobs.map((j) => '- $j').join('\n'))
    ..writeln()
    ..writeln('## GitHub secrets')
    ..writeln()
    ..writeln('Add these in **Settings → Secrets and variables → Actions**:')
    ..writeln();
  for (final secret in secrets) {
    final tag = secret.required ? 'required' : 'optional';
    buffer.writeln('- `${secret.name}` ($tag) — ${secret.description}');
  }
  buffer
    ..writeln()
    ..writeln('## Branch protection')
    ..writeln()
    ..writeln(
      'Require the `analyze` and `architecture_audit` jobs on pull requests '
      'before merging to main.',
    );
  if (githubOwner != null && githubRepo != null) {
    buffer
      ..writeln()
      ..writeln('## Status badge')
      ..writeln()
      ..writeln('```markdown')
      ..writeln(readmeBadgeSnippet(githubOwner, githubRepo))
      ..writeln('```');
  }
  return buffer.toString();
}
