import '../config.dart';
import 'ci_provider.dart';
import 'ci_template_shared.dart';
import 'ci_workflow_spec.dart';

Map<String, String> generateCircleCiFiles({
  required CiWorkflowSpec spec,
  required ToolkitConfig config,
}) {
  final flutterImage = providerConfigString(
    spec.providerConfig,
    'flutter_image',
    fallback: 'cirrusci/flutter:stable',
  );
  final resourceClass = providerConfigString(
    spec.providerConfig,
    'resource_class',
    fallback: 'medium',
  );

  final jobs = <String>[];

  if (spec.hasCiJobs) {
    final analyzeCmds = sharedAnalyzeCommands(spec);
    jobs.add('''
  analyze:
    docker:
      - image: $flutterImage
    resource_class: $resourceClass
    steps:
      - checkout
      - run:
          name: Quality gates
          command: |
${analyzeCmds.map((c) => '            $c').join('\n')}
''');
  }

  if (spec.androidAab) {
    jobs.add('''
  android_release:
    docker:
      - image: $flutterImage
    resource_class: $resourceClass
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: apt-get update && apt-get install -y openjdk-17-jdk
      - run:
          name: Build AAB
          command: |
            echo "\$ENV_FILE" > .env.ci
            export ENV_FILE_PATH=.env.ci
            flutter pub get
            ${sharedAndroidBuildCommand(spec, config)}
      - store_artifacts:
          path: build/app/outputs/bundle
''');
  }

  if (spec.iosIpa) {
    jobs.add('''
  ios_release:
    macos:
      xcode: latest
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: Build IPA
          command: |
            echo "\$ENV_FILE" > .env.ci
            export ENV_FILE_PATH=.env.ci
            flutter pub get
            cd ios && pod install && cd ..
            ${sharedIosBuildCommand(spec, config)}
      - store_artifacts:
          path: build/ios/ipa
''');
  }

  final workflowJobs = <String>[];
  if (spec.hasCiJobs) workflowJobs.add('      - analyze');
  if (spec.androidAab) workflowJobs.add('      - android_release');
  if (spec.iosIpa) workflowJobs.add('      - ios_release');

  final yaml = '''
# Generated by Flutter Project Setup Toolkit — CircleCI
# Docs: https://circleci.com/docs/
# Add ENV_FILE and signing secrets in Project Settings → Environment Variables

version: 2.1

jobs:
${jobs.join('\n')}

workflows:
  flutter_ci:
    jobs:
${workflowJobs.join('\n')}
''';

  return {'.circleci/config.yml': yaml};
}
