import '../config.dart';
import 'ci_provider.dart';
import 'ci_template_shared.dart';
import 'ci_workflow_spec.dart';

Map<String, String> generateCodemagicFiles({
  required CiWorkflowSpec spec,
  required ToolkitConfig config,
}) {
  final workflowName = providerConfigString(
    spec.providerConfig,
    'workflow_name',
    fallback: 'Flutter CI',
  );
  final instanceType = providerConfigString(
    spec.providerConfig,
    'instance_type',
    fallback: 'mac_mini_m2',
  );
  final flutterChannel = sharedFlutterVersionLine(spec);

  final scripts = <String>['flutter pub get'];
  scripts.addAll(sharedAnalyzeCommands(spec).skip(1));

  final buildScripts = <String>[];
  if (spec.androidAab) {
    buildScripts.add('''
        - name: Android AAB
          script: |
            echo "\$ENV_FILE" > .env.ci
            export ENV_FILE_PATH=.env.ci
            flutter pub get
            ${sharedAndroidBuildCommand(spec, config)}''');
  }
  if (spec.iosIpa) {
    buildScripts.add('''
        - name: iOS IPA
          script: |
            echo "\$ENV_FILE" > .env.ci
            export ENV_FILE_PATH=.env.ci
            flutter pub get
            cd ios && pod install && cd ..
            ${sharedIosBuildCommand(spec, config)}''');
  }

  final allScripts = spec.hasCiJobs
      ? scripts.map((s) => '      - $s').join('\n')
      : buildScripts.join('\n');

  final releaseBlock = buildScripts.isNotEmpty && spec.hasCiJobs
      ? '\n${buildScripts.join('\n')}'
      : (buildScripts.isNotEmpty ? allScripts : '');

  final yaml = '''
# Generated by Flutter Project Setup Toolkit — Codemagic
# Docs: https://docs.codemagic.io/yaml/yaml-getting-started/
# Configure ENV_FILE and signing in Codemagic → Environment variables

workflows:
  flutter_ci:
    name: $workflowName
    max_build_duration: ${spec.hasReleaseJobs ? 90 : 45}
    instance_type: $instanceType
    environment:
      flutter: $flutterChannel
      groups:
        - codemagic
      vars:
        ENV_FILE: Encrypted(...) # paste env file contents in Codemagic UI
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
${spec.hasCiJobs ? allScripts : ''}$releaseBlock
    artifacts:
      - build/**/*
''';

  return {'codemagic.yaml': yaml};
}
