import '../config.dart';

/// Generates `.github/workflows/flutter-release.yml` for a configured Flutter project.
String generateGitHubActionsWorkflow({
  required ToolkitConfig config,
  String toolkitPackage = 'flutter_project_setup_toolkit',
}) {
  final envNames = config.environments.keys.toList();
  final defaultEnv = config.defaultEnvironment ?? 'dev';
  final androidFlavor = config.build.androidFlavor;
  final iosScheme = config.build.iosScheme;

  final envListYaml = envNames.map((e) => '          - $e').join('\n');

  return '''
# Generated by Flutter Project Setup Toolkit — customize secrets before enabling store upload.
name: Flutter release

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build
        required: true
        default: $defaultEnv
        type: choice
        options:
$envListYaml

env:
  SKIP_CONFIRM: "1"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart analyze --fatal-infos
      - run: dart test
      - name: Architecture audit
        run: dart run $toolkitPackage:architecture_audit --project . --json
        continue-on-error: false

  android:
    needs: analyze
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Write env file from secret
        env:
          ENV_FILE_CONTENTS: \${{ secrets.ENV_FILE }}
        run: |
          mkdir -p .secrets
          echo "\$ENV_FILE_CONTENTS" > .secrets/ci.env
      - run: flutter pub get
      - name: Build Android AAB
        run: |
          flutter build appbundle --release \\
            --dart-define-from-file=.secrets/ci.env \\
            ${androidFlavor != null ? '--flavor $androidFlavor \\' : ''}
            --dart-define=APP_ENV=\${{ github.event.inputs.environment || '$defaultEnv' }}

  ios:
    needs: analyze
    runs-on: macos-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Write env file from secret
        env:
          ENV_FILE_CONTENTS: \${{ secrets.ENV_FILE }}
        run: |
          mkdir -p .secrets
          echo "\$ENV_FILE_CONTENTS" > .secrets/ci.env
      - run: flutter pub get
      - name: Build iOS IPA
        run: |
          flutter build ipa --release \\
            --dart-define-from-file=.secrets/ci.env \\
            --export-options-plist=ios/ExportOptions.plist \\
            ${iosScheme != 'Runner' ? '--scheme $iosScheme \\' : ''}
            --dart-define=APP_ENV=\${{ github.event.inputs.environment || '$defaultEnv' }}
      # Signing: configure MATCH_PASSWORD, APP_STORE_CONNECT_API_KEY in repo secrets.
''';
}

String generateFastlaneStub() {
  return '''
# Generated Fastlane stub — fill credentials before upload lanes.

default_platform(:android)

platform :android do
  desc "Upload to Play internal track (configure service account)"
  lane :internal do
    # gradle(task: "bundle", build_type: "Release")
    # upload_to_play_store(track: "internal", aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
end

platform :ios do
  desc "Upload to TestFlight (configure API key)"
  lane :beta do
    # build_app(workspace: "ios/Runner.xcworkspace", scheme: "Runner")
    # upload_to_testflight
  end
end
''';
}
