import '../config.dart';
import 'ci_workflow_paths.dart';
import 'ci_workflow_spec.dart';

/// Generates GitHub Actions workflow YAML files for the given spec and project config.
Map<String, String> generateGitHubWorkflowFiles({
  required CiWorkflowSpec spec,
  required ToolkitConfig config,
}) {
  final merged = _mergeSpecWithConfig(spec, config);
  if (merged.pipelineMode == CiPipelineMode.split &&
      merged.hasCiJobs &&
      merged.hasReleaseJobs) {
    return {
      CiWorkflowPaths.ciWorkflow: _generateCiWorkflow(merged, config),
      CiWorkflowPaths.releaseWorkflow:
          _generateReleaseWorkflow(merged, config),
    };
  }
  if (merged.pipelineMode == CiPipelineMode.split && merged.hasCiJobs) {
    return {CiWorkflowPaths.ciWorkflow: _generateCiWorkflow(merged, config)};
  }
  return {
    CiWorkflowPaths.releaseWorkflow: _generateUnifiedWorkflow(merged, config),
  };
}

/// Backward-compatible single-file generator used by setup wizard.
String generateGitHubActionsWorkflow({
  required ToolkitConfig config,
  String toolkitPackage = 'flutter_project_setup_toolkit',
  CiWorkflowSpec? spec,
}) {
  final effective = spec ??
      CiWorkflowSpec.fromPreset(CiWorkflowPreset.release).copyWith(
        toolkitPackage: toolkitPackage,
        defaultEnv: config.defaultEnvironment ?? 'dev',
        environmentNames: config.environments.keys.toList(),
      );
  final files = generateGitHubWorkflowFiles(spec: effective, config: config);
  return files.values.first;
}

String generateFastlaneStub({bool firebase = false}) {
  final firebaseLane = firebase
      ? '''
  desc "Distribute to Firebase App Distribution (configure service account)"
  lane :firebase do
    # firebase_app_distribution(
    #   app: ENV["FIREBASE_APP_ID"],
    #   groups: "internal-testers",
    #   release_notes: "CI build",
    #   firebase_cli_token: ENV["FIREBASE_TOKEN"],
    #   android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab",
    # )
  end
'''
      : '';
  return '''
# Generated Fastlane stub — fill credentials before upload lanes.

default_platform(:android)

platform :android do
  desc "Upload to Play internal track (configure service account)"
  lane :internal do
    # gradle(task: "bundle", build_type: "Release")
    # upload_to_play_store(track: "internal", aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
$firebaseLane
end

platform :ios do
  desc "Upload to TestFlight (configure API key)"
  lane :beta do
    # build_app(workspace: "ios/Runner.xcworkspace", scheme: "Runner")
    # upload_to_testflight
  end
end
''';
}

String generateActSecretsExample() {
  return '''
# Copy to .act.secrets (gitignored) for local act runs.
# Never commit real secrets.
ENV_FILE=
ANDROID_KEYSTORE_BASE64=
ANDROID_KEYSTORE_PASSWORD=
MATCH_PASSWORD=
''';
}

CiWorkflowSpec _mergeSpecWithConfig(CiWorkflowSpec spec, ToolkitConfig config) {
  return spec.copyWith(
    defaultEnv: config.defaultEnvironment ?? spec.defaultEnv,
    environmentNames: config.environments.keys.isNotEmpty
        ? config.environments.keys.toList()
        : spec.environmentNames,
  );
}

String _generateCiWorkflow(CiWorkflowSpec spec, ToolkitConfig config) {
  final triggers = _triggerBlock(spec, includeTags: false);
  return '''
# Generated by Flutter Project Setup Toolkit — PR quality gates (ubuntu only).
name: Flutter CI

$triggers

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

env:
  SKIP_CONFIRM: "1"

jobs:
${_ciJobsBlock(spec, config)}
''';
}

String _generateReleaseWorkflow(CiWorkflowSpec spec, ToolkitConfig config) {
  final triggers = _releaseTriggerBlock(spec);
  final envListYaml = spec.environmentNames.map((e) => '          - $e').join('\n');
  return '''
# Generated by Flutter Project Setup Toolkit — release builds (configure secrets before store upload).
name: Flutter release

$triggers
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build
        required: true
        default: ${spec.defaultEnv}
        type: choice
        options:
$envListYaml

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

env:
  SKIP_CONFIRM: "1"

jobs:
${_releaseJobsBlock(spec, config, needsJob: null)}
''';
}

String _generateUnifiedWorkflow(CiWorkflowSpec spec, ToolkitConfig config) {
  final triggers = _triggerBlock(spec, includeTags: spec.tagTrigger);
  final envListYaml = spec.workflowDispatch
      ? spec.environmentNames.map((e) => '          - $e').join('\n')
      : '';
  final dispatchBlock = spec.workflowDispatch
      ? '''
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build
        required: true
        default: ${spec.defaultEnv}
        type: choice
        options:
$envListYaml
'''
      : '';

  return '''
# Generated by Flutter Project Setup Toolkit — customize secrets before enabling store upload.
name: Flutter release

$triggers$dispatchBlock
concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

env:
  SKIP_CONFIRM: "1"

jobs:
${_ciJobsBlock(spec, config, jobPrefix: 'ci_')}
${_releaseJobsBlock(spec, config, needsJob: spec.hasCiJobs ? 'ci_analyze' : null, jobPrefix: 'release_')}
''';
}

String _triggerBlock(CiWorkflowSpec spec, {required bool includeTags}) {
  final parts = <String>[];
  if (spec.onPush) {
    parts.add('''  push:
    branches: [main, master]''');
  }
  if (spec.onPullRequest) {
    parts.add('''  pull_request:
    branches: [main, master]''');
  }
  if (includeTags && spec.tagTrigger) {
    parts.add('''  push:
    tags: ['v*']''');
  }
  if (parts.isEmpty) {
    parts.add('  workflow_dispatch:');
  }
  return 'on:\n${parts.join('\n')}';
}

String _releaseTriggerBlock(CiWorkflowSpec spec) {
  final parts = <String>[];
  if (spec.onPush) {
    parts.add('''  push:
    branches: [main, master]''');
  }
  if (spec.tagTrigger) {
    parts.add('''  push:
    tags: ['v*']''');
  }
  if (parts.isEmpty) {
    return 'on:\n  workflow_dispatch:';
  }
  return 'on:\n${parts.join('\n')}';
}

String _ciJobsBlock(
  CiWorkflowSpec spec,
  ToolkitConfig config, {
  String jobPrefix = '',
}) {
  final jobs = <String>[];
  if (spec.pathFilters) {
    jobs.add(_pathFilterJob(jobPrefix: jobPrefix));
  }
  if (spec.analyze || spec.formatCheck || spec.architectureAudit || spec.coverage) {
    jobs.add(_analyzeJob(
      spec,
      config,
      jobPrefix: jobPrefix,
      needsPathFilter: spec.pathFilters,
    ));
  }
  return jobs.join('\n');
}

String _pathFilterJob({String jobPrefix = ''}) {
  return '''
  ${jobPrefix}changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      flutter: \${{ steps.filter.outputs.flutter }}
    steps:
${_checkoutStep()}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            flutter:
              - 'lib/**'
              - 'test/**'
              - 'pubspec.yaml'
              - 'pubspec.lock'
              - 'android/**'
              - 'ios/**'
''';
}

String _releaseJobsBlock(
  CiWorkflowSpec spec,
  ToolkitConfig config, {
  String? needsJob,
  String jobPrefix = '',
}) {
  final jobs = <String>[];
  if (spec.androidAab) {
    jobs.add(_androidJob(spec, config, needs: needsJob, jobPrefix: jobPrefix));
  }
  if (spec.iosIpa) {
    jobs.add(_iosJob(spec, config, needs: needsJob, jobPrefix: jobPrefix));
  }
  if (spec.firebaseAppDistribution && spec.androidAab) {
    jobs.add(_firebaseJob(spec, needs: '${jobPrefix}android'));
  }
  return jobs.join('\n');
}

String _analyzeJob(
  CiWorkflowSpec spec,
  ToolkitConfig config, {
  String jobPrefix = '',
  bool needsPathFilter = false,
}) {
  final steps = <String>[
    _checkoutStep(),
    _flutterSetup(spec),
    '      - run: flutter pub get',
  ];
  if (spec.analyze) {
    steps.add('      - run: dart analyze --fatal-infos');
    steps.add('      - run: dart test');
  }
  if (spec.coverage) {
    steps.add('      - run: flutter test --coverage');
    steps.add('''      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: warn''');
  }
  if (spec.formatCheck) {
    steps.add('      - run: dart format --set-exit-if-changed .');
  }
  if (spec.architectureAudit) {
    steps.add('''      - name: Architecture audit
        run: dart run ${spec.toolkitPackage}:architecture_audit --project . --json''');
  }
  steps.add(_pubCacheSteps());

  final needsLine = needsPathFilter
      ? 'needs: ${jobPrefix.isEmpty ? 'changes' : '${jobPrefix}changes'}'
      : '';
  final ifLine = needsPathFilter
      ? 'if: needs.${jobPrefix.isEmpty ? 'changes' : '${jobPrefix}changes'}.outputs.flutter == \'true\''
      : '';

  return '''
  ${jobPrefix}analyze:
    ${needsLine.isNotEmpty ? '$needsLine' : ''}
    ${ifLine.isNotEmpty ? '$ifLine' : ''}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
${steps.join('\n')}
''';
}

String _androidJob(
  CiWorkflowSpec spec,
  ToolkitConfig config, {
  String? needs,
  String jobPrefix = '',
}) {
  final androidFlavor = config.build.androidFlavor;
  final buildCmd = spec.useToolkitScripts
      ? './scripts/build-android.sh'
      : '''flutter build appbundle --release \\
            --dart-define-from-file=.secrets/ci.env \\
            ${androidFlavor != null ? '--flavor $androidFlavor \\' : ''}
            --dart-define=APP_ENV=\${{ github.event.inputs.environment || '${spec.defaultEnv}' }}''';

  final artifactSteps = spec.uploadArtifacts
      ? '''
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/**/*.aab
          if-no-files-found: warn
'''
      : '';

  return '''
  ${jobPrefix}android:
    ${needs != null ? 'needs: $needs' : ''}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
${_checkoutStep()}
${_flutterSetup(spec)}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
${_gradleCacheSteps()}
      - name: Write env file from secret
        env:
          ENV_FILE_CONTENTS: \${{ secrets.ENV_FILE }}
        run: |
          mkdir -p .secrets
          echo "\$ENV_FILE_CONTENTS" > .secrets/ci.env
      - run: flutter pub get
      - name: Build Android AAB
        run: |
          $buildCmd
$artifactSteps''';
}

String _iosJob(
  CiWorkflowSpec spec,
  ToolkitConfig config, {
  String? needs,
  String jobPrefix = '',
}) {
  final iosScheme = config.build.iosScheme;
  final buildCmd = spec.useToolkitScripts
      ? './scripts/build-ios-ipa.sh'
      : '''flutter build ipa --release \\
            --dart-define-from-file=.secrets/ci.env \\
            --export-options-plist=ios/ExportOptions.plist \\
            ${iosScheme != 'Runner' ? '--scheme $iosScheme \\' : ''}
            --dart-define=APP_ENV=\${{ github.event.inputs.environment || '${spec.defaultEnv}' }}''';

  final artifactSteps = spec.uploadArtifacts
      ? '''
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: warn
'''
      : '';

  return '''
  ${jobPrefix}ios:
    ${needs != null ? 'needs: $needs' : ''}
    runs-on: macos-latest
    timeout-minutes: 45
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
${_checkoutStep()}
${_flutterSetup(spec)}
      - name: Write env file from secret
        env:
          ENV_FILE_CONTENTS: \${{ secrets.ENV_FILE }}
        run: |
          mkdir -p .secrets
          echo "\$ENV_FILE_CONTENTS" > .secrets/ci.env
      - run: flutter pub get
      - name: Build iOS IPA
        run: |
          $buildCmd
$artifactSteps      # Signing: configure MATCH_PASSWORD, APP_STORE_CONNECT_API_KEY in repo secrets.
''';
}

String _firebaseJob(CiWorkflowSpec spec, {required String needs}) {
  return '''
  firebase_distribution:
    needs: $needs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name != 'pull_request'
    steps:
${_checkoutStep()}
      - name: Firebase App Distribution (stub)
        run: |
          echo "Configure Fastlane firebase_app_distribution lane and FIREBASE_SERVICE_ACCOUNT secret"
          echo "See https://firebase.google.com/docs/app-distribution"
''';
}

String _checkoutStep() => '      - uses: actions/checkout@v4';

String _flutterSetup(CiWorkflowSpec spec) {
  final archLine = spec.actCompatFlutterX64
      ? '\n          architecture: x64'
      : '';
  final versionLine = spec.flutterVersion != null && spec.flutterVersion!.isNotEmpty
      ? '\n          flutter-version: \'${spec.flutterVersion}\''
      : '';
  return '''      - uses: subosito/flutter-action@v2
        with:
          channel: stable$versionLine$archLine''';
}

String _pubCacheSteps() => '''
      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: \${{ runner.os }}-pub-\${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            \${{ runner.os }}-pub-
''';

String _gradleCacheSteps() => '''
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: \${{ runner.os }}-gradle-\${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            \${{ runner.os }}-gradle-
''';
