import '../config.dart';
import 'ci_provider.dart';
import 'ci_template_shared.dart';
import 'ci_workflow_spec.dart';

Map<String, String> generateGitLabCiFiles({
  required CiWorkflowSpec spec,
  required ToolkitConfig config,
}) {
  final flutterImage = providerConfigString(
    spec.providerConfig,
    'flutter_image',
    fallback: 'ghcr.io/cirruslabs/flutter:stable',
  );
  final defaultBranch = providerConfigString(
    spec.providerConfig,
    'default_branch',
    fallback: 'main',
  );

  final stages = <String>[];
  if (spec.hasCiJobs) stages.add('test');
  if (spec.hasReleaseJobs) stages.add('build');

  final jobs = <String>[];

  if (spec.hasCiJobs) {
    final analyzeCmds = sharedAnalyzeCommands(spec);
    jobs.add('''
analyze:
  stage: test
  image: $flutterImage
  rules:
    - if: \$CI_PIPELINE_SOURCE == "merge_request_event"
    - if: \$CI_COMMIT_BRANCH == "$defaultBranch"
  script:
${yamlScriptBlock(analyzeCmds, indent: '    ')}
''');
  }

  if (spec.androidAab) {
    jobs.add('''
android_release:
  stage: build
  image: $flutterImage
  rules:
    - if: \$CI_COMMIT_BRANCH == "$defaultBranch"
      when: manual
  before_script:
    - apt-get update && apt-get install -y openjdk-17-jdk
    - echo "\$ENV_FILE" > .env.ci
    - export ENV_FILE_PATH=.env.ci
  script:
    - flutter pub get
    - ${sharedAndroidBuildCommand(spec, config)}
  artifacts:
    paths:
      - build/app/outputs/bundle/**/*.aab
    expire_in: 14 days
''');
  }

  if (spec.iosIpa) {
    jobs.add('''
ios_release:
  stage: build
  tags:
    - saas-macos-medium-m1
  rules:
    - if: \$CI_COMMIT_BRANCH == "$defaultBranch"
      when: manual
  before_script:
    - echo "\$ENV_FILE" > .env.ci
    - export ENV_FILE_PATH=.env.ci
  script:
    - flutter pub get
    - ${sharedIosBuildCommand(spec, config)}
  artifacts:
    paths:
      - build/ios/ipa/*.ipa
    expire_in: 14 days
''');
  }

  final yaml = '''
# Generated by Flutter Project Setup Toolkit — GitLab CI
# Docs: https://docs.gitlab.com/ee/ci/
# Set CI/CD variables: ENV_FILE, ANDROID_KEYSTORE_* (see CI_SETUP.md)

stages:
${stages.map((s) => '  - $s').join('\n')}

${jobs.join('\n')}
''';

  return {'.gitlab-ci.yml': yaml};
}
